name: commandeplus
description: application de gestion des flux de commandes
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.6
  woocommerce_api: ^0.1.0
  wakelock: ^0.6.2
  provider: ^6.1.1
  google_fonts: ^4.0.4
  package_info_plus: ^3.1.2
  http: ^0.13.6
  url_launcher: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true



  assets:
      - assets/logo/
      - assets/image/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

